language: node_js
node_js:
  - "iojs"
  - "8.9.4"
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
before_install:
  - npm i -g npm@5.6.0
script: npm start
cache:
  directories:
   - "node_modules"
